# Generated by Django 6.0.4 on 2026-05-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_anonyme', models.CharField(editable=False, max_length=20, unique=True)),
                ('type_signalement', models.CharField(choices=[('corruption', 'Corruption judiciaire'), ('violation', 'Violation de droits'), ('fuite', 'Fuite de donnees')], max_length=20)),
                ('tribunal_concerne', models.CharField(max_length=200)),
                ('date_incident', models.DateField()),
                ('description_chiffree', models.TextField()),
                ('preuves_chiffrees', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('recu', 'Recu'), ('en_cours', 'En cours de traitement'), ('traite', 'Traite'), ('classe', 'Classe sans suite')], default='recu', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('checksum', models.CharField(editable=False, max_length=64)),
            ],
        ),
    ]
