# Generated by Django 6.0.4 on 2026-05-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('dossiers_total', models.IntegerField(default=0)),
                ('dossiers_en_attente', models.IntegerField(default=0)),
                ('dossiers_traites', models.IntegerField(default=0)),
                ('magistrats', models.IntegerField(default=0)),
            ],
        ),
    ]
