# Generated by Django 6.0.4 on 2026-05-05 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('critical', 'Critique')], max_length=10)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tribunal', models.CharField(blank=True, max_length=50)),
                ('resolue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Deconnexion'), ('consultation', 'Consultation dossier'), ('modification', 'Modification dossier'), ('signalement', 'Signalement soumis'), ('export', 'Export de donnees'), ('acces_refuse', 'Acces refuse')], max_length=30)),
                ('tribunal', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('immuable', models.BooleanField(default=True, editable=False)),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-horodatage'],
            },
        ),
        migrations.CreateModel(
            name='JuridictionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('magistrat', 'Magistrat'), ('greffier', 'Greffier'), ('avocat', 'Avocat'), ('opj', 'Officier de Police Judiciaire'), ('admin', 'Administrateur')], max_length=20)),
                ('tribunal', models.CharField(choices=[('TGI Yaounde', 'TGI Yaounde'), ('TGI Douala', 'TGI Douala'), ('TGI Bafoussam', 'TGI Bafoussam')], max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='juridiction_role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
